-- MySQL Script generated by MySQL Workbench
-- 2017년 02월 05일 (일) 오후 10시 33분 32초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema yoongoodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yoongoodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yoongoodb` DEFAULT CHARACTER SET utf8 ;
USE `yoongoodb` ;

-- -----------------------------------------------------
-- Table `yoongoodb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoongoodb`.`user` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'index',
  `id` VARCHAR(45) NOT NULL COMMENT 'user\'s primary id.',
  `nickname` VARCHAR(45) NOT NULL COMMENT 'user\'s nickname',
  `email` VARCHAR(45) NOT NULL COMMENT 'user\'s email',
  `img` VARCHAR(45) NULL COMMENT 'user\'s img',
  `date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `nickName_UNIQUE` (`nickname` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = 'user info';


-- -----------------------------------------------------
-- Table `yoongoodb`.`user_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoongoodb`.`user_flag` (
  `message` VARCHAR(45) NOT NULL COMMENT 'created message of flag message.',
  `location` VARCHAR(45) NOT NULL COMMENT 'created location of flag message.',
  `date` DATETIME(6) NOT NULL COMMENT 'created date of flag message.\n',
  `user_idx` INT(11) NOT NULL,
  INDEX `fk_user_flag_user_idx` (`user_idx` ASC),
  PRIMARY KEY (`user_idx`),
  CONSTRAINT `fk_user_flag_user`
    FOREIGN KEY (`user_idx`)
    REFERENCES `yoongoodb`.`user` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
